
// Code
// Testcase
// Testcase
// Test Result
// 389. Find the Difference
// Easy
// Topics
// Companies
// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

 

// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

// Input: s = "", t = "y"
// Output: "y"
 

// Constraints:

// 0 <= s.length <= 1000
// t.length == s.length + 1
// s and t consist of lowercase English letters.

/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function(s, t) {
    let count = {}

    for (let char of s){
        count[char] = (count[char] || 0) + 1
    }

    for ( let char of t){
        if (!count[char]){
            return char
        } else count[char]--
    }
};


// for this problem we create a hashmap and then run through it with our t taking away each letters count until we find
// the letter that finds our count to be at 0, we then know that that will be our extra character and return that.